// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://ovzejtweuxqtwswlgmnx.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im92emVqdHdldXhxdHdzd2xnbW54Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzMwMjcwODcsImV4cCI6MjA0ODYwMzA4N30.tlh-jvStON5NceLMMZfEL0sIYx7Ymtt2hGhddZQ9a3I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);